### ISSUE TITLE
Missing modules detected in the models folder.

### ISSUE THREAD

**Issue by jinzhuangdou** [CellProfiling/subcell-embed#2]
Cell In[9], line 27
     25 from data.collate_fn import collate_fn_train
     26 from data.get_datasets import get_datasets
---> 27 from models.get_models import get_model_dict
     28 from models.lightning.callbacks.result_callback import ResultSaveCallback
     29 from models.lightning.callbacks.gc_callback import ScheduledGarbageCollector

File /rsrch1/bcb/kchen_group/jdou/ST_explore/subcell-embed/models/__init__.py:10
      8 from .attention_pooling import *
      9 from .mmcr import *
---> 10 from .online_triplet import *
     11 from .w_mse import *
     12 from .centroid_diff import *

ModuleNotFoundError: No module named 'models.online_triplet'

**Comment by aktgpt** [comment]
Thanks for pointing it out. Fixed in the recent commit.
